# Generated by Django 5.2.5 on 2025-08-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='강의 제목')),
                ('content', models.TextField(verbose_name='강의 설명')),
                ('thumbnail_image', models.ImageField(upload_to='thumbnail/%Y/%m/%d/', verbose_name='썸네일')),
                ('video_file', models.FileField(upload_to='video/%Y/%m/%d/', verbose_name='강의영상')),
                ('pdf_file', models.FileField(upload_to='file/%Y/%m/%d/', verbose_name='강의자료')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
        ),
    ]
