# Generated by Django 5.2.5 on 2025-08-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.CharField(choices=[('TELC_A1', 'Telc A1'), ('TELC_A2', 'Telc A2'), ('TELC_B1', 'Telc B1'), ('TELC_B2', 'Telc B2'), ('TELC_C1', 'Telc C1 Hochschule'), ('TESTDAF_PAPER', 'TestDaF(종이 시험)'), ('TESTDAF_DIGITAL', 'TestDaF(디지털 시험)'), ('GOETHE', 'Goethe-Zertifikat')], max_length=30, unique=True, verbose_name='시험유형 코드')),
                ('exam_label', models.CharField(max_length=50, verbose_name='시험유형 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_code', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=10, unique=True, verbose_name='레벨 코드')),
                ('level_label', models.CharField(max_length=50, verbose_name='레벨 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_code', models.CharField(choices=[('GRAMMAR', 'Grammatik(문법)'), ('READING', 'Lesen(읽기)'), ('LISTENING', 'Hören(듣기)'), ('SPEAKING', 'Sprechen(말하기)'), ('WRITING', 'Schreiben(쓰기)'), ('VOCABULARY', 'Wortschatz(어휘)'), ('STRATEGY', 'Prüfungsstrategie(시험전략)'), ('MOCK', 'Probeprüfung(모의고사)'), ('ONE_DAY', 'Ein-Tages-Kurs(원데이코스)')], max_length=30, unique=True, verbose_name='강의유형 코드')),
                ('theme_label', models.CharField(max_length=50, verbose_name='강의유형 이름')),
            ],
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='게시일'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='file/%Y/%m/%d/', verbose_name='강의자료'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/%Y/%m/%d/', verbose_name='썸네임'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video/%Y/%m/%d/', verbose_name='강의 영상'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='exams',
            field=models.ManyToManyField(to='web.examtype', verbose_name='시험'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='levels',
            field=models.ManyToManyField(to='web.level', verbose_name='레벨'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='themes',
            field=models.ManyToManyField(to='web.theme', verbose_name='유형'),
        ),
    ]
