# Generated by Django 5.2.5 on 2025-08-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_examtype_level_theme_alter_coursematerial_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='theme_code',
            field=models.CharField(choices=[('NONE', 'Normaler Kurs(일반강의)'), ('GRAMMAR', 'Grammatik(문법)'), ('READING', 'Lesen(읽기)'), ('LISTENING', 'Hören(듣기)'), ('SPEAKING', 'Sprechen(말하기)'), ('WRITING', 'Schreiben(쓰기)'), ('VOCABULARY', 'Wortschatz(어휘)'), ('STRATEGY', 'Prüfungsstrategie(시험전략)'), ('MOCK', 'Probeprüfung(모의고사)'), ('ONE_DAY', 'Ein-Tages-Kurs(원데이코스)')], max_length=30, unique=True, verbose_name='강의유형 코드'),
        ),
    ]
