# Generated by Django 5.2.5 on 2025-08-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_theme_theme_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='exam_code',
            field=models.CharField(choices=[('NONE', 'Normaler Kurs(일반강의)'), ('TELC_A1', 'Telc A1'), ('TELC_A2', 'Telc A2'), ('TELC_B1', 'Telc B1'), ('TELC_B2', 'Telc B2'), ('TELC_C1', 'Telc C1 Hochschule'), ('TESTDAF_PAPER', 'TestDaF(종이 시험)'), ('TESTDAF_DIGITAL', 'TestDaF(디지털 시험)'), ('GOETHE', 'Goethe-Zertifikat')], max_length=30, unique=True, verbose_name='시험유형 코드'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_code',
            field=models.CharField(choices=[('GRAMMAR', 'Grammatik(문법)'), ('READING', 'Lesen(읽기)'), ('LISTENING', 'Hören(듣기)'), ('SPEAKING', 'Sprechen(말하기)'), ('WRITING', 'Schreiben(쓰기)'), ('VOCABULARY', 'Wortschatz(어휘)'), ('STRATEGY', 'Prüfungsstrategie(시험전략)'), ('MOCK', 'Probeprüfung(모의고사)'), ('ONE_DAY', 'Ein-Tages-Kurs(원데이코스)')], max_length=30, unique=True, verbose_name='강의유형 코드'),
        ),
    ]
